apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-deploy
spec:
 replicas: 4
 selector:
   matchLabels:
     app: deploy-app
 template:
   metadata:
      name: deploy-pod
      labels:
       app: deploy-app
   spec:
     containers:
     - image: awasay/job_finder:v1
       name: container1
       imagePullPolicy: IfNotPresent
